Repository UXCorpRangel/js-conf-cl-2025, pull requests merged in 2025-02, with the labels that each got.

#55 fix: adjust alignment properties in HeroSection for improved layout
  src/pages/_index/HeroSection.astro
Labels: bug

#56 feat: add privacy link
  src/components/ui/Card.astro
  src/pages/_index/SliderSection.astro
Labels: enhancement

#57 Ready to prod
  src/components/ui/Card.astro
  src/components/ui/Countdown.astro
  src/pages/_index/HeroSection.astro
  src/pages/_index/SliderSection.astro
Labels: enhancement

#62 fix: increase z-index of social component for improved layering
  src/components/ui/Social.astro
Labels: bug

#58 chore(deps): update dependencies in package.json
  package.json
Labels: enhancement

#61 fix: update Footer component to use local badge image with improved loading attributes
  public/images/uxcorprangel-badge.svg
  src/components/ui/Footer.astro
Labels: enhancement

#63 fix: adjust styles in Slider component for responsive and fix body overflow (#60)
  src/components/ui/Slider.astro
  src/layouts/Base.astro
  src/styles/slider.css
Labels: enhancement

#64 feat: add StaticCountdown component and replace Countdown in Parallax Section
  src/components/ui/StaticCountdown.astro
  src/pages/_index/CountdownSection.astro
  src/pages/_index/ParallaxSection.astro
Labels: enhancement

#65 fix: update accessibility issues
  src/components/ui/ClickToScroll.astro
  src/components/ui/Social.astro
  src/pages/_index/HeroSection.astro
  src/pages/_index/ParallaxSection.astro
Labels: enhancement

#66 chore: fix Open Graph image preview
  public/og/og.jpg
  src/layouts/Layout.astro
Labels: bug, enhancement
