Repository UXCorpRangel/js-conf-cl-2025, pull requests merged in 2025-01, with the labels that each got.

#4 docs: :memo: add figma link
  README.md
Labels: documentation

#10 feat: ✨ add click to scroll component
  src/components/ui/ClickToScroll.astro
  src/icons/chevron-down.svg
Labels: enhancement

#15 Add button component
  src/components/ui/Button.astro
  src/components/ui/Social.astro
  src/icons/arrow-right.svg
  src/icons/chevron-down.svg
  src/icons/e-mail.svg
  src/icons/facebook.svg
  src/icons/github.svg
  src/icons/instagram.svg
  src/icons/linkedin.svg
  src/icons/x.svg
  src/styles/globals.css
Labels: enhancement

#18 feat: create slider component
  package.json
  src/components/ui/Slider.astro
  src/data/slider-images.ts
  src/images/.gitkeep
  src/images/slider/segunda-edicion-jsconf-01.jpg
  src/images/slider/segunda-edicion-jsconf-02.jpg
  src/pages/index.astro
  src/scripts/.gitkeep
  src/scripts/slider.ts
  src/styles/slider.css
Labels: enhancement

#19 feat: ✨ add countdown component
  package.json
  src/components/ui/Countdown.astro
Labels: enhancement

#21 Components
  .github/dependabot.yml
  package.json
  public/media/jsconf-dia2evento-501.webp
  public/media/jsconf-dia2evento-611.webp
  public/og/og.jpg
  public/robots.txt
  src/components/Bento.astro
  src/components/OpenGraph.astro
  src/components/ui/Button.astro
  src/components/ui/CallToAction.astro
  src/components/ui/CallToActionSection.astro
  src/components/ui/Card.astro
  src/components/ui/ClickToScroll.astro
  src/components/ui/Countdown.astro
  src/components/ui/Footer.astro
  src/components/ui/Slider.astro
  src/components/ui/Social.astro
  src/data/constants.ts
  src/data/slider-images.ts
  src/icons/arrow-right.svg
  src/icons/chevron-down.svg
  src/icons/e-mail.svg
  src/icons/facebook.svg
  src/icons/github.svg
  src/icons/instagram.svg
  src/icons/linkedin.svg
  src/icons/x.svg
  src/images/.gitkeep
  src/images/slider/segunda-edicion-jsconf-01.jpg
  src/images/slider/segunda-edicion-jsconf-02.jpg
  src/layouts/Base.astro
  src/pages/_index/BentoGridSection.astro
  src/pages/_index/CountdownSection.astro
  src/pages/_index/HeroSection.astro
  src/pages/_index/LinkCardGrid.astro
  src/pages/index.astro
  src/scripts/.gitkeep
  src/scripts/slider.ts
  src/styles/.gitkeep
  src/styles/globals.css
  src/styles/slider.css
Labels: enhancement

#30 refactor: stars component
  src/components/ui/Stars.astro
  src/pages/_index/HeroSection.astro
  src/scripts/starfield.ts
Labels: enhancement

#31 feat: 💄 update global styles for improved typography and layout
  src/styles/globals.css
Labels: enhancement

#33 feat: create parallax effect and section
  src/components/ui/ClickToScroll.astro
  src/components/ui/Countdown.astro
  src/contracts/index.ts
  src/contracts/parallax.type.ts
  src/data/parallax-images.ts
  src/images/parallax/capa-01.png
  src/images/parallax/capa-02.png
  src/images/parallax/capa-03.png
  src/images/parallax/capa-04.png
  src/pages/_index/HeroSection.astro
  src/pages/_index/ParallaxSection.astro
  src/pages/index.astro
  src/scripts/parallax.ts
Labels: enhancement

#34 fix: add missing else block in Countdown component for correct logic
  src/components/ui/Countdown.astro
Labels: bug

#35 Estilos del header
  public/logo/logo-conf2025.svg
  src/components/ui/CallToAction.astro
  src/images/assets/jsconf-chile-2025-logo.webp
  src/pages/_index/HeroSection.astro
  src/styles/globals.css
  tsconfig.json
Labels: enhancement

#36 Fix/parallax
  src/components/ui/Countdown.astro
  src/pages/_index/BentoGridSection.astro
  src/pages/_index/HeroSection.astro
  src/pages/_index/ParallaxSection.astro
  src/styles/globals.css
Labels: enhancement

#37 Fix/bento grid
  public/media/jsconf-dia2evento-501.webp
  public/media/jsconf-dia2evento-611.webp
  src/components/Bento.astro
  src/components/ui/Card.astro
  src/images/assets/jsconf-chile-2023-dia-2-005.webp
  src/images/assets/jsconf-dia-2-evento-50.webp
  src/pages/_index/BentoGridSection.astro
Labels: enhancement

#38 Feat/general styles
  src/components/ui/Card.astro
  src/components/ui/Footer.astro
  src/pages/_index/BentoGridSection.astro
  src/pages/_index/HeroSection.astro
  src/pages/_index/SliderSection.astro
Labels: enhancement

#39 Pre Release
  public/media/jsconf-dia2evento-501.webp
  public/media/jsconf-dia2evento-611.webp
  src/components/Bento.astro
  src/components/ui/CallToAction.astro
  src/components/ui/Card.astro
  src/components/ui/ClickToScroll.astro
  src/components/ui/Countdown.astro
  src/components/ui/Footer.astro
  src/components/ui/Stars.astro
  src/contracts/index.ts
  src/contracts/parallax.type.ts
  src/data/parallax-images.ts
  src/icons/Location.astro
  src/icons/location.svg
  src/images/assets/jsconf-chile-2023-dia-2-005.webp
  src/images/assets/jsconf-chile-2025-logo.webp
  src/images/assets/jsconf-dia-2-evento-50.webp
  src/images/parallax/capa-01.png
  src/images/parallax/capa-02.png
  src/images/parallax/capa-03.png
  src/images/parallax/capa-04.png
  src/pages/_index/BentoGridSection.astro
  src/pages/_index/HeroSection.astro
  src/pages/_index/ParallaxSection.astro
  src/pages/_index/SliderSection.astro
  src/pages/index.astro
  src/scripts/parallax.ts
  src/scripts/starfield.ts
  src/styles/globals.css
  tsconfig.json
Labels: enhancement

#40 chore: refactor images
  package.json
  src/components/Bento.astro
  src/images/assets/jsconf-chile-2023-dia-2-005.webp
  src/images/assets/jsconf-chile-2023-dia-2-acreditacion.png
  src/images/assets/jsconf-chile-2024-dia-2-evento.png
  src/images/assets/jsconf-chile-2025-logo.png
  src/images/assets/jsconf-chile-2025-logo.webp
  src/images/assets/jsconf-dia-2-evento-50.webp
  src/pages/_index/HeroSection.astro
Labels: enhancement

#44 Update Pre Release
  package.json
  src/components/Bento.astro
  src/components/ui/Footer.astro
  src/components/ui/Social.astro
  src/images/assets/jsconf-chile-2023-dia-2-005.webp
  src/images/assets/jsconf-chile-2023-dia-2-acreditacion.png
  src/images/assets/jsconf-chile-2024-dia-2-evento.png
  src/images/assets/jsconf-chile-2025-logo.png
  src/images/assets/jsconf-chile-2025-logo.webp
  src/images/assets/jsconf-dia-2-evento-50.webp
  src/pages/_index/HeroSection.astro
  src/styles/globals.css
Labels: enhancement
